const TRANSLATIONS = {
  // Ингредиенты
  "Coffee Beans": "Кофейные бобы",
  "Coconut": "Кокос",
  "Cocoa Powder": "Какао-порошок",
  "Flour": "Мука",
  "Apple": "Яблоко",
  "Eggs": "Яйца",
  "Lettuce": "Салат",
  "Fish": "Рыба",
  "Orange": "Апельсин",
  "Milk": "Молоко",
  "Matcha Powder": "Порошок матча",
  "Whipping Cream": "Сливки",
  "Beef": "Говядина",
  "Butter": "Масло",
  "Red Beans": "Красные бобы",
  "Strawberry": "Клубника",
  "Onion": "Лук",
  "Pork": "Свинина",
  "Salt": "Соль",
  "Cookies": "Печенье",
  "Cheese": "Сыр",
  "Ham": "Ветчина",
  "Sugar": "Сахар",
  "Skibbles": "Скиблс",
  "Tomato": "Помидор",

  // Блюда
  "Coconut Latte": "Кокосовый латте",
  "Ice Mocha": "Мокко со льдом",
  "Apple Pie": "Яблочный пирог",
  "Tomato & Fried Egg": "Круассан с помидором и жареным яйцом",
  "Tuna Sandwich": "Сэндвич с тунцом",
  "Amber Glamor": "Янтарный гламур",
  "Matacha Lava Mousse": "Лавовый мусс с матча",
  "Snowy Latte": "Снежный Латте",
  "Thick-Cut Fresh Beef Sandwich": "Сэндвич с толстым куском свежей говядины",
  "Red Bean & Butter Crossiant": "Круассан с маслом и красной фасолью",
  "Strawberry Box Cake": "Клубничный торт",
  "Orange Hot Coffee": "Горячий апельсиновый кофе",
  "Pork Cutlet": "Сэндвич со свининой",
  "Coconut Macchiato": "Кокосовый макиато",
  "Matcha Latte with Milk Cap": "Матча латте с молочной шапкой",
  "Tiramisu": "Тирамису",
  "Ham & Cheese": "Круассан с ветчиной и сыром",
  "Caramel & Cocoa Mille-Feuille": "Мильфей с карамелью и какао",

  // Персонажи
  "Nanally": "Нанали",
  "Sakiri": "Сакири",
  "Skia": "Ския",
  "Baicang": "Байканг",
  "Mint": "Минт",
  "Haniel": "Ханиэль",
  "Adler": "Адлер",
  "Dafodil": "Даффодил",
  "Edgar": "Эдгар",
  "Aurelia": "Аурелия",
  "Chiz": "Чиз",
  "Lacrimosa": "Лакримоза",

  // Типы блюд и категории (для выпадающего списка трендов)
  "Beverages": "Напитки",
  "Main Dishes": "Основные блюда",
  "Desserts": "Десерты",
  "Fruit": "Фрукты",
  "Dish Types": "Типы блюд",
  "Categories": "Категории",
  "Ingredients": "Ингредиенты",

  // Валюта
  "Fons": "Фонс",

  // Типы навыков (опционально, для красоты)
  "Price_Flat": "Цена",
  "Traffic_Flat": "Трафик",
  "Price_Multiply": "Множ. цены",
  "Traffic_Multiply": "Множ. трафика",
  "Any": "Любой",
  "None": "—"
};